### ISSUE TITLE
Hello world example.

### ISSUE THREAD

**Issue by ghost** [david-vanderson/dvui-demo#1]
Please create a simple hello world example.

I cant figure out how to use gui for a simple hello world program because I don't understand how to correctly build anything with Zig. Please create a single simple hello-world so I can get started. Thanks.

**Comment by david-vanderson** [comment]
This is supposed to be the "hello world" examples, but I see I didn't explicitly say to run the command.  Does running `zig build run-standalone-sdl` work for you?

**Comment by ghost** [comment]
Your examples work perfectly thank you. I'm just confused trying to make any library work with zig. Sorry, TMI all at once with zig.

Looking over your build.zip, it makes more sense to me now.

I think what I will do for my app: Using a copy of your example, put your gui code in src/gui, my code in src/app, and edit build.zip so the paths are corrected.

Again, thank you. Kind regards, joe budd

**Comment by david-vanderson** [comment]
No problem.  That plan sounds good to me.

It can be difficult right now because zig is changing so fast.  If you have more issues let me know!
