### ISSUE TITLE
avoid unnecessary page allocation in the main loop?

### ISSUE THREAD

**Issue by cedric-h** [david-vanderson/dvui-demo#2]
I'm curious about this bit right here in the sdl standalone example:
https://github.com/david-vanderson/gui-demo/blob/3b2e87d5b9e0abd22f6f7c3fa32ead5e3126494b/standalone-sdl.zig#L29C1-L29C1

I'm familiar with the idea of an arena allocator that lasts for a frame or two, into which you can dump all of your dynamically sized temporaries which don't need to live longer than a single frame. This way, they're automatically cleared away at the end of the frame, when you no longer need them.

What I don't understand -- and maybe I'm wrong and you can go on ahead and learn me something -- is why you would deinit and then recreate this allocator every frame, instead of simply resetting it?

Is there some implementation detail of the page allocator that makes this irrelevant? (e.g. you're going to get the same page you allocated last frame back at 0 cost.) Does it just not have a function to reset its allocation pointer and other assorted state?

Thanks,
Ced :)

**Comment by cedric-h** [comment]
Imagine the case where the application typically needs only a single page of RAM to render all of its GUI, but every once in a while a graph is updated or some other computation is done that requires a couple extra pages of RAM. By reusing the allocator across frames, you could potentially avoid lag spikes where the application struggles to re-allocate those pages of RAM, simply by sitting on them for the lifetime of the application.

I suppose allocating a few pages every frame is hardly much of a performance hit and beyond the single page case it's more of a "should I be a RAM hog?" or "should I avoid allocator lag spikes?" question ...

**Comment by david-vanderson** [comment]
Great question - I just messed that up!  Give me some time to fix it up.  I'll make the change in the main repo (https://github.com/david-vanderson/dvui) and then sync it here.

Thanks!

**Comment by david-vanderson** [comment]
Does that look better?

**Comment by cedric-h** [comment]
Yeah, that looks great!

Glad I could help 😅
